### ISSUE TITLE
Pythonハンズオンの資料について

### ISSUE THREAD

**Issue by akimach** [tfug-utsunomiya/201806_ML_handson#1]
TFUG Utsunomiya #12 ハンズオンに向けて、色々と決めてたり資料作りとかできたらないいなと思いIssueを立てました。

ハンズオンの内容では基本的にデータ解析や機械学習で使われるPythonに絞ろうと思ってます。具体的には、以下の流れでやろうかなと思ってます。「あれが必要、これが要らない」とかあったら大歓迎です。

* Python・PyDataについて
* Jupyter Notebook・Colaboratoryを使ってみよう
* Pythonの基本的な文法・データ構造を学ぶ
* データ分析や機械学習でよく使うPyData入門（Numpy・Matplotlib・Pandas etc）
* 復習！Pythonでゼロからニューラルネットを作ってみる
* TensorFlow でディープラーニングに挑戦

@wbydo と 横山くん（githubのアカウントを問い合わせ中）が担当したい、これをやりたいということがあったら教えてください。

**Comment by wbydo** [comment]
招待ありがとう！

基本的に全部の項、どれでも前向きに担当出来ます。

ただ、「Jupyter Notebook・Colaboratoryを使ってみよう」の項だけはちょっと避けたいかも。
Colaboratoryをあんまり普段遣いしないから痒いところに手を届かせる紹介が出来なそうです。

「TensorFlow でディープラーニングに挑戦」もTensorFlowの普段遣い度的にちょい不安
ただ、TensorFlowUserGroupだしって意味でモチベーションはあります。

「Pythonの基本的な文法・データ構造を学ぶ」「データ分析や機械学習でよく使うPyData入門」
この辺のエッセンス抽出していい感じにまとめるのは出来そうかなと思います。

テーマの不足は心配ないと思いますが、
ボリューム多く感じるので時間配分的なものがちょっと心配かなと。
特に「復習！Pythonでゼロからニューラルネットを作ってみる」がボリューミーに感じます。

**Comment by kuroneko913** [comment]
招待ありがとうございます。

基本的にこの流れでいいと思いますが、すべてを時間内にやりきるのはきついかなと思います。

特にゼロからニューラルネットを作るのコーナーはやると理解が深まるとは思いますが、やり方によっては、これだけで1回を使ってしまう気がします。

pyData入門に関しては、研究や趣味でいじってはいるので、自分の知識の整理もかねてやってみたいと思います。

jupyterとcolabratoryは使い始めたばかりなので、基本的な使い方ぐらいしか知りません。

Tensorflowで、ディープラーニングに挑戦は、CNNを使ってMNISTのデモを動かすのがいいのかな、と思いました。捻りがないか……

**Comment by akimach** [comment]
@wbydo @kuroneko913 ありがとうございます。

> 特に「復習！Pythonでゼロからニューラルネットを作ってみる」がボリューミーに感じます。

そうなんですよね。復習のために数式からNumpyに書いてみるプロセスがあるといいと思ってます。ちょっと考えておきます。

**Comment by akimach** [comment]
単純なパーセプトロンならいけるんじゃないかな。Back propagationはスルー。

時間に関しては延長するか、2回に分けるという手もあります。

**Comment by wbydo** [comment]
>復習のために数式からNumpyに書いてみるプロセスがあるといいと思ってます。

そこが目的なのであれば、
ゼロからニューラルネットだとちょっと範囲が広いので、単純パーセプトロンにするなり取り扱う理論の難易度を下げた方が良いかなと。

単純パーセプトロンの実装よりさらに簡易的にやるなら、2次元の回帰問題かなと思います。

単純パーセプトロンにしろ2次元回帰問題にしろ勾配効果法による最適化問題になりますが数学的ハードルは大丈夫でしょうか。

**Comment by akimach** [comment]
@wbydo 最急降下法ってそんなにハードル高いかな？

とりあえずパーセプトロンでやってみて、みんなにレビューをもらおう。

**Comment by wbydo** [comment]
@akimach
いや、最急降下法のハードルはそんなに高くないとは思います。
一応対象はどの辺なのかなっていうことの確認の意味で。

**Comment by akimach** [comment]
少し間が空いてしまってすみません。

1. Python・PyDataについて（全体像） #2
    * akimach
2. Jupyter Notebook・Colaboratoryを使ってみよう #3
    * akimach
3. Pythonの基本的な文法・データ構造を学ぶ #4
    * @wbydo 
4. データ分析や機械学習でよく使うPyData入門（Numpy・Matplotlib・Pandas etc） #5
    * @kuroneko913 @wbydo 
5. 復習！Pythonでパーセプトロンを作ってみよう！ #6
    * akimach

という割当でどうでしょうか。一番ウェイトを占めているのは3と特に4だと思ってます。2人は同じ研究室だし会って話し合ってもらえると嬉しいです。他にやりたいところがあってら言ってください

**Comment by akimach** [comment]
個別にissue立てておきます。

**Comment by wbydo** [comment]
確認しました。
詳しくは個別issueで

**Comment by kuroneko913** [comment]
確認しました。

**Comment by akimach** [comment]
@wbydo 

基本的には、スライドとJupyter Notebookを用意してください

**Comment by wbydo** [comment]
@akimach
Jupyter Notebookを用意してRIZE（Notebookをプレゼンぽく表示するやつ）を使って映そうと思ってたんだけどどうでしょう？

**Comment by akimach** [comment]
closeします。お疲れ様でした。
